version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=0
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - POSTGRES_DB=siha_rent
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
        depends_on:
            - localhost  
    localhost:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=siha_rent
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
        volumes:
            - pgdata:/var/lib/postgresql/data/
        ports:
            - "5436:5432"
        depends_on:
            - pgadmin
    pgadmin:
        image: dpage/pgadmin4
        
        ports:
        - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin  
      
volumes:
    pgdata:
