# Generated by Django 5.0 on 2023-12-09 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('description', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UCAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('max_takeoff_weight', models.FloatField(blank=True, null=True)),
                ('max_speed_mach', models.FloatField(blank=True, null=True)),
                ('max_altitude_feet', models.IntegerField(blank=True, null=True)),
                ('autonomous_takeoff_and_landing', models.BooleanField(default=False)),
                ('unit_rental_price', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('aircraft_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucav_category', to='uav_app.aircraftcategory')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucav_brand', to='uav_app.brand')),
            ],
            options={
                'verbose_name': 'UCAV',
                'verbose_name_plural': 'UCAVs',
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_user', to=settings.AUTH_USER_MODEL)),
                ('ucav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_ucav', to='uav_app.ucav')),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'ordering': ('start_date', 'end_date', 'price'),
            },
        ),
    ]
