# Generated by Django 5.0 on 2023-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftcategory',
            options={'ordering': ('name', 'id'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='ucav',
            options={'ordering': ('name', 'id'), 'verbose_name': 'UCAV', 'verbose_name_plural': 'UCAVs'},
        ),
        migrations.AlterField(
            model_name='aircraftcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
