# Generated by Django 5.0 on 2023-12-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav_app', '0004_alter_rental_start_date_alter_rental_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
